name: CI Push
on:
  push:
    branches:
      - vercel_deploy

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci --loglevel=error
      - run: npm run lint --if-present
      - run: npm run typecheck --if-present
      - run: npm run build
