name: CI Push
on:
  push:
    branches:
      - vercel_deploy
jobs:
  verify-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Verify branch
        run: |
          if [ "$GITHUB_REF" != "refs/heads/vercel_deploy" ]; then
            echo "Not on vercel_deploy branch."
            exit 1
          fi
