name: CI
on:
  push:
    branches:
      - main
      - vercel_deploy
  pull_request:
jobs:
  build:
    name: Lint, install and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --loglevel=error
      - name: Lint (CI)
        run: npm run lint:ci
      - name: Build
        run: npm run build
